
title: "The Responsible Security and Privacy Lab"
description: "A Research Group at Université libre de Bruxelles, École polytechnique, Brussels, Belgium"

show_downloads: false
google_analytics:

author:
  name: Jan Tobias Muehlberg


# Dinky Theme: https://github.com/pages-themes/dinky
remote_theme: pages-themes/dinky@v0.2.0

plugins:
  - jekyll-remote-theme

markdown: kramdown

